apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: eks-gitops-platform
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/nrobertio/eks-gitops-platform.git
  ref:
    branch: main
