replicaCount: 2

image:
  repository: ghcr.io/nrobertio/demo-api
  tag: "0.1.0"
  pullPolicy: IfNotPresent

env:
  APP_ENV: dev

serviceAccount:
  create: true
  # Set to the IRSA role ARN from Terraform output demo_api_irsa_role_arn.
  annotations: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
